---
# For configuration documentation visit https://gethomepage.dev/configs/settings/

title: "Bluewave Homelab"
favicon: "https://auth.bluewave.work/favicon.ico"
theme: dark
color: slate
cardBlur: none
headerStyle: clean
useEqualHeights: true
target: _blank

layout:
  Management & Ingress:
    style: row
    columns: 3
  Observability & Telemetry:
    style: row
    columns: 3
  AI & Intelligence:
    style: row
    columns: 3
  Cloud Storage & Photos:
    style: row
    columns: 2

showStats: true
quicklaunch:
  searchDescriptions: true
  hideInternetSearch: false
  showSearchSuggestions: true
  provider: google
  target: _blank
