---
# For configuration documentation visit https://gethomepage.dev/configs/settings/

title: "Bluewave Homelab"
favicon: "https://bluewave.work/favicon.ico"
theme: dark
color: slate
background:
  image: "https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&w=2000&q=80"
  blur: "sm"
  brightness: 40

layout:
  Management & Ingress:
    style: row
    columns: 3
  Observability & Telemetry:
    style: row
    columns: 3
  AI & Intelligence:
    style: row
    columns: 3
  Cloud Storage & Photos:
    style: row
    columns: 2

headerStyle: clean
showStats: true
quicklaunch:
  searchDescriptions: true
  hideInternetSearch: false
  showSearchSuggestions: true
  provider: google
