---
# For widget documentation visit https://gethomepage.dev/widgets/

- search:
    provider: google
    target: _blank
    focus: false

- datetime:
    text_size: xl
    format:
      timeStyle: short
      dateStyle: full
      hour12: false

- openmeteo:
    label: "Weather"
    latitude: 36.8982
    longitude: 10.1815
    timezone: Africa/Tunis
    units: metric

- resources:
    label: "System Load"
    cpu: true
    memory: true
